---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    chart: "{{ .Chart.Name }}"
    app: "{{ .Values.fullname }}"
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 8080
  selector:
    app: {{ .Values.fullname }}
